AliBucketName: testbucket
AliAccessKeyId: youraccesskeyid
AliAccessKeySecret: youraccesskeysecret
AliEndpoint: oss-cn-shenzhen.aliyuncs.com

UserName: root
Password: password

# Hash keys should be at least 32 bytes long
HashKey: vQz78hsVOFeckbWpSujBI2twmapLjV7V

# Block keys should be 16 bytes (AES-128) or 32 bytes (AES-256) long.
# Shorter keys may weaken the encryption used.
BlockKey: YxkI4yYNJMZQzHBQ